config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/ramen_registration',  to:'ramen_lists#new'
  post '/ramen_registration',  to: 'ramen_lists#create'
  get '/review_post',  to:'review_lists#new'
  post '/review_post',  to: 'review_lists#create'
  resources :ramen_lists
  resources :review_lists
end

app/models/ramen_list.rb
class RamenList < ActiveRecord::Base
  has_many :review_lists, dependent: :destroy
  validates :shop_name,  presence:true
  validates :shop_name_furi,  presence:true, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/ , message: 'は全角カタカナで入力して下さい'}
  validates :prefecture, presence: true
  validates :place, presence: true
  validates :tel, length: {allow_blank:true, in: 12..13}, format: { with: /\A(\A\d{2,5}-\d{1,4}-\d{4}+\z)?\z/ , message: 'は不正な値です。ハイフン付きの半角数字で入力してください' }
  
  def self.search(search,ordertype,pref) 
    # if search
    #   if pref =="全国"
    #     if ordertype == "created_at"
    #       where(['shop_name LIKE ?', "%#{search}%"]).order('created_at desc')
    #     elsif ordertype == "avg-points"
    #       where(['shop_name LIKE ?', "%#{search}%"]).left_joins(:review_lists).group(:id).order('avg(points) desc,shop_name_furi')
    #     elsif ordertype == "aiueo"
    #       where(['shop_name LIKE ?', "%#{search}%"]).order('shop_name_furi')
    #     elsif ordertype == "review-count"
    #       where(['shop_name LIKE ?', "%#{search}%"]).left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi')
    #     else
    #       where(['shop_name LIKE ?', "%#{search}%"]).order('created_at desc')
    #     end
    #   else
    #     if ordertype == "created_at"
    #       where(['shop_name LIKE ?', "%#{search}% "]).where(['place LIKE ?', "%#{pref}%"]).order('created_at desc')
    #     elsif ordertype == "avg-points"
    #       where(['shop_name LIKE ?', "%#{search}%"]).where(['place LIKE ?', "%#{pref}%"]).left_joins(:review_lists).group(:id).order('avg(points) desc,shop_name_furi')
    #     elsif ordertype == "aiueo"
    #       where(['shop_name LIKE ?', "%#{search}%"]).where(['place LIKE ?', "%#{pref}%"]).order('shop_name_furi')
    #     elsif ordertype == "review-count"
    #       where(['shop_name LIKE ?', "%#{search}%"]).where(['place LIKE ?', "%#{pref}%"]).left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi')
    #     else
    #       where(['shop_name LIKE ?', "%#{search}%"]).where(['place LIKE ?', "%#{pref}%"]).order('created_at desc')
    #     end
    #   end

    if search
     # debugger
      if pref =="全国" || pref == ""
        @search=where(['shop_name LIKE ?', "%#{search}%"])
      else
        @search=where(['shop_name LIKE ?', "%#{search}%"]).where(['prefecture LIKE ?', "%#{pref}%"])
      end
      if ENV["RACK_ENV"] == "production"
        if ordertype == "created_at"
          @search.order('created_at desc')
        elsif ordertype == "avg-points"
          @search.left_joins(:review_lists).group(:id).order('avg(points) desc NULLS LAST,shop_name_furi COLLATE "ja_JP.utf8" asc')
        elsif ordertype == "aiueo"
          @search.order('shop_name_furi COLLATE "ja_JP.utf8" asc')
        elsif ordertype == "review-count"
          @search.left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi COLLATE "ja_JP.utf8" asc')
        else
          @search.order('created_at desc')
        end
      else
        if ordertype == "created_at"
          @search.order('created_at desc')
        elsif ordertype == "avg-points"
          @search.left_joins(:review_lists).group(:id).order('avg(points) desc,shop_name_furi')
        elsif ordertype == "aiueo"
          @search.order('shop_name_furi')
        elsif ordertype == "review-count"
          @search.left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi')
        else
          @search.order('created_at desc')
        end
      end
    else
      #all
      if ENV["RACK_ENV"] == "production"
        if ordertype == "created_at"
          all.order('created_at desc')
        elsif ordertype == "avg-points"
          all.left_joins(:review_lists).group(:id).order('avg(points) desc NULLS LAST,shop_name_furi COLLATE "ja_JP.utf8" asc')
          #joins(:review_lists).group(:ramen_list_id).order('points desc').average(:points)
        elsif ordertype == "aiueo"
          all.order('shop_name_furi COLLATE "ja_JP.utf8" asc')
        elsif ordertype == "review-count"
          all.left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi COLLATE "ja_JP.utf8" asc')
        else
          all.order('created_at desc')
        end
      else
        if ordertype == "created_at"
          all.order('created_at desc')
        elsif ordertype == "avg-points"
          all.left_joins(:review_lists).group(:id).order('avg(points) desc,shop_name_furi')
          #joins(:review_lists).group(:ramen_list_id).order('points desc').average(:points)
        elsif ordertype == "aiueo"
          all.order('shop_name_furi')
        elsif ordertype == "review-count"
          all.left_joins(:review_lists).group(:id).order('count(review) desc,shop_name_furi')
        else
          all.order('created_at desc')
        end
      end
    end
  end
end

app/controllers/ramen_lists_controller.rb
class RamenListsController < ApplicationController
  
  def index
  #  @ramen_lists = if params[:search]
  #    RamenList.paginate(page: params[:page]).where('shop_name LIKE ?', "%#{params[:search]}%")
  #  else
  #    @ramen_lists= RamenList.paginate(page: params[:page],:per_page => 10)
  #  end
    @ordertype = params[:ordertype]
    #debugger
    if params[:prefecture].nil?
      @pref = ""
    else
      @pref = params[:prefecture]
    end
    @ramen_lists = RamenList.paginate(page: params[:page], :per_page => 10).search(params[:search],params[:ordertype],@pref)
  end
  
  def show
    @ramen_list = RamenList.find(params[:id])
    @review_lists = @ramen_list.review_lists.paginate(page: params[:page], :per_page => 10)
    @review_point_avg = @ramen_list.review_lists.average(:points)
  end
  
  def new
    @ramen_list= RamenList.new
  end
  
  def create
    @ramen_list = RamenList.new(ramen_params)
    if @ramen_list.save
      flash[:info] = "お店を登録しました！"
      redirect_to ramen_list_path(@ramen_list.id)
    else
      render 'new'
    end  
  end

  def edit
    @ramen_list = RamenList.find(params[:id])
  end
  
  def update
        @ramen_list = RamenList.find(params[:id])
    if @ramen_list.update_attributes(ramen_params)
      flash[:success] = "お店の情報を更新しました！"
      redirect_to @ramen_list
    else
      render 'edit'
    end
  end

  private
  
    def ramen_params
      params.require(:ramen_list).permit(:shop_name, :shop_name_furi,:prefecture, :place, :tel, :business_hours,
       :regular_holiday, :parking_area, :access, :other)
    end
end

app/helpers/ramen_lists_helper.rb
module RamenListsHelper
  def now_sort(sort)
    if params[:ordertype] == nil && sort=="created_at"
      false
    elsif sort=="created_at" && params[:ordertype] == ""
      false
    else
      sort != params[:ordertype]
    end
  end
  
  def list_count(search,pref)
    if search == nil && pref == ""
      RamenList.all.count
    elsif pref == "全国"
      RamenList.where(['shop_name LIKE ?', "%#{search}%"]).count
    else
      RamenList.where(['shop_name LIKE ?', "%#{search}%"]).where(['prefecture LIKE ?', "%#{pref}%"]).count
    end
  end
end

app/views/ramen_lists/_form.html.erb
<%= form_for(@ramen_list, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :"店舗名","店舗名" %><span class="red">※</span>
  <%= f.text_field :shop_name, placeholder: "例:ラーメン屋　1号　新宿店", class: 'form-control' %>
  
  <%= f.label :"店舗名フリガナ","店舗名フリガナ" %><span class="red">※</span>
  <%= f.text_field :shop_name_furi, placeholder: "例:ラーメンヤ　イチゴウ　シンジュクテン", class: 'form-control' %>

  <%= f.label :"都道府県","都道府県" %><span class="red">※</span>
  <%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name, :prompt => "選択してください", class: 'form-control' %>
  <%= f.label :"市区町村","市区町村" %><span class="red">※</span>
  <%= f.text_field :place, placeholder: "例:新宿区ＸＸＸ XXX-xx", class: 'form-control' %>

  <%= f.label :"電話番号","電話番号" %>
  <%= f.text_field :tel, placeholder: "ハイフン付きで入力。例:090-1234-5678", class: 'form-control' %>

  <%= f.label :"営業時間","営業時間" %>
  <%= f.text_field :business_hours, placeholder: "例:11:00~15:00", class: 'form-control' %>


  <%= f.label :"定休日","定休日" %>
  <%= f.text_field :regular_holiday, placeholder: "例:年中無休", class: 'form-control' %>


  <%= f.label :"駐車場","駐車場" %>
  <%= f.text_field :parking_area, placeholder: "例:有、10台", class: 'form-control' %>


  <%= f.label :"アクセス","アクセス" %>
  <span class="ramen_textarea"><%= f.text_area :access, placeholder: "最寄駅、最寄バス停から所要時間、行き方等", class: 'form-control' %></span>


 <%= f.label :"備考","備考" %>
 <span class="ramen_textarea"><%= f.text_area :other, placeholder: "店に関する情報等", class: 'form-control' %></span>


  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/ramen_lists/edit.html.erb
<% provide(:title, @ramen_list.shop_name+"の編集") %>
<% provide(:url, ramen_list_path) %>
<% provide(:button_text, '変更') %>
<h1>お店の編集</h1>
<h2>
  <span class="red">※</span>
  は必須入力項目です
</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/ramen_lists/index.html.erb
<% provide(:title, 'ラーメン屋リスト') %>
<h1>ラーメン屋リスト</h1>


<h2>検索機能</h2>
<h4>店舗名</h3>
<%= form_tag(ramen_lists_path, method: :get) do %>
    <%= text_field_tag :search, params[:search] %>
    <%= hidden_field_tag :ordertype, @ordertype %>
    <h4>エリア</h4>
    <%#= collection_select :pre ,:prefecture, JpPrefecture::Prefecture.all, :name, :name,:selected => @pref %>
    <%= select_tag :prefecture,
      options_from_collection_for_select(JpPrefecture::Prefecture.all, "name", "name",
                                         selected: @pref ),:prompt=>"全国" %>
    <%= submit_tag '検索' , :name => nil %>

<% end %>
<%= will_paginate @customers %><br>
<% if now_sort("created_at") %>
  <%= link_to "新着順",ramen_lists_path(:search =>params[:search], :ordertype =>"created_at",:prefecture => @pref)  %>
<% else %>
  新着順
<% end %>
<% if now_sort("aiueo") %>
  <%= link_to "あいうえお順",ramen_lists_path(:search =>params[:search], :ordertype =>"aiueo",:prefecture => @pref) %>
<% else %>
  あいうえお順
<% end %>
<% if now_sort("avg-points") %>
  <%= link_to "ポイント順",ramen_lists_path(:search =>params[:search], :ordertype =>"avg-points",:prefecture => @pref) %>
<% else %>
  ポイント順
<% end %>
<% if now_sort("review-count") %>
  <%= link_to "レビュー数順",ramen_lists_path(:search =>params[:search], :ordertype =>"review-count",:prefecture => @pref) %>
<% else %>
  レビュー数順
<% end %>
<h2>登録件数(<%= list_count(params[:search],@pref) %>)</h2>
<ul class="ramen_lists">
  <% @ramen_lists.each do |list| %>
    <li>
      <span class="shop_name">
        <%= link_to list.shop_name, list %>
      </span>
      <span class="place">
       エリア: <%= list.prefecture + list.place %>
      </span>
      <span class="ave">
        <% if list.review_lists.any? %>
          平均点: <%= format("%.2f",  list.review_lists.average(:points)) %>
        <% else %>
          平均点: --.--
        <% end %>
      </span>
      <span class="review_count">
        レビュー数: <%= list.review_lists.count %>件
      </span>
    </li>
  <% end %>
</ul>

<%= will_paginate @customers %>

app/views/ramen_lists/new.html.erb
<% provide(:title, 'お店の追加') %>
<% provide(:url, ramen_registration_path) %>
<% provide(:button_text, '追加') %>
<h1>お店の追加</h1>
<h2>
  <span class="red">※</span>
  は必須入力項目です
</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/ramen_lists/show.html.erb
<% provide(:title, @ramen_list.shop_name) %>
<div class="row">
  <aside class="col-md-4">
    <div class="shop_sidebar">
    <section class="ramen_list_info">
      <h1>
        <%= @ramen_list.shop_name %>
      </h1>
      <h2>
        <%= @ramen_list.shop_name_furi %>
      </h2>
    </section>
    <section class="stats">
      <div class=".alt-table-responsive">
        <span class="avg_points">
          <table class="table">
            <tr>
              <th>
                平均点
              </th>
              <td>
                <div class="points">
                  <% if @ramen_list.review_lists.any? %>
                   <%= format("%.2f", @review_point_avg) %>
                  <% else %>
                    --.--
                  <% end %>
                </span>
              </td>
            </tr>
          </table>
        </span>
      </div>
      <div class=".alt-table-responsive ">
        <span class="shop_status">
          <table class="table table-bordered">
            <tr>
              <th>
                エリア
                </th>
              <td>
                <%= @ramen_list.prefecture + @ramen_list.place %>
              </td>
            </tr>
             <tr>
              <th>
                電話番号
                </th>
              <td>
                <%= @ramen_list.tel %>
              </td>
            </tr>
            <tr>
              <th>
                営業時間
                </th>
              <td>
                <%= @ramen_list.business_hours %>
              </td>
            </tr>
            <tr>
              <th>
                定休日
                </th>
              <td>
                <%= @ramen_list.regular_holiday %>
              </td>
            </tr>
            <tr>
              <th>
                駐車場
                </th>
              <td>
                <%= @ramen_list.parking_area %>
              </td>
            </tr>
            <tr>
              <th>
                アクセス
                </th>
              <td>
                <%= simple_format(@ramen_list.access) %>
              </td>
            </tr>
            <tr>
              <th>
                備考
                </th>
              <td>
                <%= simple_format(@ramen_list.other) %>
              </td>
            </tr>
            
          </table>
        </span>
      </div>
    </section>
    </div>
    <span><%= link_to "お店の情報を編集する",edit_ramen_list_path(@ramen_list.id) %></span>
  </aside>
  <div class="col-md-8">
    <% if @ramen_list.review_lists.any? %>
      <h3>レビュー数 (<%= @ramen_list.review_lists.count %>)</h3>
      <h4><%= link_to "このお店のレビューを投稿する", review_post_path(:ramen_id => @ramen_list.id) %></h4>
      <%= will_paginate @review_lists %>
      <ol class="review_lists">
        <%= render @review_lists %>
      </ol>
      <%= will_paginate @review_lists %>
    <% else %>  
      <h3>レビュー数 (0)</h3>
      <h4><%= link_to "このお店のレビューを投稿する", review_post_path(:ramen_id => @ramen_list.id) %></h4>
    <% end %>
  </div>
</div>