config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/ramen_registration',  to:'ramen_lists#new'
  post '/ramen_registration',  to: 'ramen_lists#create'
  get '/review_post',  to:'review_lists#new'
  post '/review_post',  to: 'review_lists#create'
  resources :ramen_lists
  resources :review_lists
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
Produced by <%= link_to "KENTA OKADA.",'http://www.shonan-it.ac.jp/contents/topics/20151104_01/index.html' %>
Supported by <%= link_to "Sonix Co., Ltd.", 'https://www.sonix.asia/' %> 
  </small>
  <nav>
    <ul>
      <li><%= link_to "らぁめんレビューDBについて",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "らぁめんレビューDB", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",   root_path %></li>
        <li><%= link_to "ラーメン屋リスト", ramen_lists_path  %></li>
        <li><%= link_to "レビューの投稿", review_post_path %></li>
        <li><%= link_to "お店の追加", ramen_registration_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>